// automatically generated by the FlatBuffers compiler, do not modify

namespace InWorldz.PrimExporter.ExpLib.ImportExport.BabylonFlatBuffers
{

using System;
using FlatBuffers;

public struct MultiMaterial : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MultiMaterial GetRootAsMultiMaterial(ByteBuffer _bb) { return GetRootAsMultiMaterial(_bb, new MultiMaterial()); }
  public static MultiMaterial GetRootAsMultiMaterial(ByteBuffer _bb, MultiMaterial obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MultiMaterial __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public string MaterialsList(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int MaterialsListLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MultiMaterial> CreateMultiMaterial(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      VectorOffset materialsListOffset = default(VectorOffset)) {
    builder.StartObject(3);
    MultiMaterial.AddMaterialsList(builder, materialsListOffset);
    MultiMaterial.AddName(builder, nameOffset);
    MultiMaterial.AddId(builder, idOffset);
    return MultiMaterial.EndMultiMaterial(builder);
  }

  public static void StartMultiMaterial(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddMaterialsList(FlatBufferBuilder builder, VectorOffset materialsListOffset) { builder.AddOffset(2, materialsListOffset.Value, 0); }
  public static VectorOffset CreateMaterialsListVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMaterialsListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MultiMaterial> EndMultiMaterial(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MultiMaterial>(o);
  }
};


}
